"""add deleted to reviewstatus enum

Revision ID: e477bea221b1
Revises: 0d2123023287
Create Date: 2025-05-30 20:25:54.124890

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e477bea221b1"
down_revision: Union[str, None] = "0d2123023287"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE reviewstatus ADD VALUE IF NOT EXISTS 'deleted'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
