name: Build & Push backend image

on:
  push:
    branches: ["main"]

env:
  AWS_REGION: ap-northeast-1
  AWS_ACCOUNT_ID: "819498957810"
  ECR_REPO: 819498957810.dkr.ecr.ap-northeast-1.amazonaws.com/nycu/docuflow

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # OIDC
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push
        run: |
          SHORT_SHA=$(git rev-parse --short=8 $GITHUB_SHA)

          docker build -t $ECR_REPO:$SHORT_SHA -t $ECR_REPO:latest .

          docker push --all-tags $ECR_REPO

      # - name: Trigger deploy workflow
      #   uses: peter-evans/workflow-dispatch@v2
      #   with:
      #     workflow: backend-deploy.yml
      #     ref: main
      #     inputs: |
      #       image_tag: ${{ github.sha }}
