name: Python CI Test with coverage

on:
  push:
    branches: ['**'] 

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Taipei"
        
      - uses: actions/checkout@v3

      - name: Set up Python 3.11.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test_requirements.txt

      - name: Set environment variable for private key
        run: echo "CLOUDFRONT_PRIVATE_KEY_BASE64=cHJpdmF0ZV9rZXk=" >> $GITHUB_ENV

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage report app/**/*.py
          coverage html
  
      - name: Check coverage threshold
        run: |
          coverage report app/**/*.py --fail-under=60
  
      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-coverage-report
          path: htmlcov
